name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[staging]')
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to staging
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/jaustis/staging
          git pull origin main

  deploy-production:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[production]')
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to production
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/jaustis/production
          git pull origin main
