name: Deploy to AWS VPS

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 deploy:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v3
   
   - name: Deploy files to server
     uses: appleboy/ssh-action@v0.1.5
     with:
       host: ${{ secrets.SERVER_HOST }}
       username: ${{ secrets.SERVER_USER }}
       key: ${{ secrets.SERVER_SSH_KEY }}
       script: |
         cd /var/www/testApp/test
         git pull origin main
